retry

diff --git a/.github/workflows/notificationsms-cicd.yml b/.github/workflows/notificationsms-cicd.yml
--- a/.github/workflows/notificationsms-cicd.yml
+++ b/.github/workflows/notificationsms-cicd.yml
@@ -112,3 +112,17 @@ jobs:
           if [ -z "$ROUTE_EXISTS" ]; then
             oc create route edge --service=${{ env.APP_NAME }}-service --port=${{ env.APP_PORT }} -n ${{ env.OPENSHIFT_NAMESPACE }}
           fi
+
+      - name: Check Deployment Status
+        id: check_status
+        run: |
+            if ! oc rollout status deployment/${{ env.APP_NAME }} -n ${{ env.OPENSHIFT_NAMESPACE }} --watch --timeout=120s; then
+              echo "::set-output name=deployment_success::false"
+            else
+              echo "::set-output name=deployment_success::true"
+            fi
+      - name: Rollback if Deployment Fails
+        if: steps.check_status.outputs.deployment_success != 'true'
+        run: |
+          echo "Deployment failed. Rolling back to previous version."
+          oc rollout undo deployment/${{ env.APP_NAME }} -n ${{ env.OPENSHIFT_NAMESPACE }}
