Update service-tests-cicd.yml

diff --git a/.github/workflows/service-tests-cicd.yml b/.github/workflows/service-tests-cicd.yml
--- a/.github/workflows/service-tests-cicd.yml
+++ b/.github/workflows/service-tests-cicd.yml
@@ -6,8 +6,18 @@ on:
     branches: [main]
 
 jobs:
+  check_branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.base_ref == 'main' && github.head_ref != 'development'
+        run: |
+          echo "ERROR: You can only merge to main from development."
+          exit 1
+          
   run-integration-tests:
     runs-on: ubuntu-latest
+    needs: check_branch
     name: Execute Integration Tests
     steps:
       - uses: actions/checkout@v3 # Check Out Code
